export { default as Facebook } from './facebook'
export { default as Mail } from './mail'
export { default as Call } from './call'
export { default as AffiliatedUnit } from './affiliated-units'
export { default as Group } from './group'
export { default as Tick } from './tick'
export { default as XMark } from './xmark'
export { default as Bin } from './bin'
